### ISSUE TITLE
Doesn't work with 0.8

### ISSUE THREAD

**Issue by alexcroox** [domoritz/leaflet-maskcanvas#16]
I believe L.TileLayer.Canvas has been removed, similar issue to https://github.com/aparshin/leaflet-boundary-canvas/issues/5?

**Comment by domoritz** [comment]
Hmm. That's bad. Unfortunately, I don't have the time to fix it but would gladly review/accept pull requests.

**Comment by shaula** [comment]
I'd also need support for maskcanvas in 0.8. I'm neither a Leaflet, nor a Javascript guru, but I could give it a try if no one else finds time.

**Comment by domoritz** [comment]
I won't have time to implement it but can review and merge.

**Comment by shaula** [comment]
Cannot assign this ticket to me - however I'll work on it.

**Comment by domoritz** [comment]
@shaula I just added you as collaborator.

**Comment by shaula** [comment]
To keep you up-to-date: I got a version working with leaflet 0.8-dev from January. Unfortunately they changed the implementation of the GridLayer afterwards, which caused troubles again. Will soon continue to find out why it does not work.

**Comment by shaula** [comment]
I added L.GridLayer.MaskCanvas. It works with the current master of leaflet (version 1.0-dev).
