### ISSUE TITLE
Mask everything except a L.geoJson layer

### ISSUE THREAD

**Issue by nikolauskrismer** [domoritz/leaflet-maskcanvas#23]
This plugin looks great. Nice work :+1: 

I was wondering if it is possible to use it to mark everything except a (Multi)Polygon (which is given as GeoJSON and saved as L.geoJson layer)??

**Comment by domoritz** [comment]
Not really (this plugin has one specific purpose) but for that you should be able to just use leaflet layers or some canvas layer directly. I hope that helps.
