### ISSUE TITLE
Circles flash each time I update

### ISSUE THREAD

**Issue by JeffJway** [domoritz/leaflet-maskcanvas#30]
Hi, sorry for disturbing.

I update the locations of the circles quite frequently and I realise that each time I update the locations of the datapoints all the circles will flash on screen as they are redrawn. Am I doing something wrong or is this expected?

I'm doing something like this:

var Overlay= L.TileLayer.maskCanvas({
		radius: 50,
		useAbsoluteRadius: true,
		color: '#f00',
		opacity: 0.4,
		noMask: true,
		lineColor: '#f00'
	});

function initz()
{
	//initialising other stuff
	..
	..
	..
	var circles = [];
	for(let x=0; x<startingData.length; x++)
	{
		circles.push([startingData.latitude, startingData.longitude, radius]);
	}
	Overlay.setData(circles);
	Overlay.addTo(Existinglayer);

	// add layer to map
	map.addLayer(Existinglayer);
}

function Update(pt)
{
	var circles = [];
	for(let x=0; x<pt.length; x++)
	{
		circles.push([pt.latitude, pt.longitude, radius]);
	}
	Overlay.setData(circles);
//I don't re-add the layer as I think it is already added and I just want to change datapoints in the layer
}
Am I doing this right?

**Comment by domoritz** [comment]
Without trying it out myself, you could create a second layer, update the points in there and then swap the layers.

**Comment by domoritz** [comment]
Closing as I’m using issues to track bugs only.
